/** Generated by scripts/sync-skills.mjs alongside the vendored skill content. */
export const SKILLS_PIN: {
  repo: string;
  /** Commit the bundled content was vendored from. Tags move; this does not. */
  commit: string;
  commitDate: string | null;
  tag: string | null;
};
